import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <style jsx>{`
        .home_img_container {
          margin: 1.5rem;
        }
      `}</style>
      <div className={styles.container}>
        <Head>
          <title>Quick Coder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className="home_img_container">
            <Image
              style={{ borderRadius: "6.25rem" }}
              src="/home_image.jpg"
              width="170px"
              height="170px"
            ></Image>
          </div>
          <h1>Welcome to Quick Coder !</h1>

          <p className={styles.description}>A blog for Curious Minds.</p>
          <h2>Popular Blogs</h2>
          <div className={styles.grid}>
            <h3>How to learn React?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, aut
              ad non hic animi, aliquid minima est corporis commodi doloribus
              nostrum, minus et nobis? Accusantium asperiores adipisci labore
              nobis nisi aspernatur natus aperiam consequuntur dignissimos?
            </p>
            <h3>How to learn React?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, aut
              ad non hic animi, aliquid minima est corporis commodi doloribus
              nostrum, minus et nobis? Accusantium asperiores adipisci labore
              nobis nisi aspernatur natus aperiam consequuntur dignissimos?
            </p>
            <h3>How to learn React?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, aut
              ad non hic animi, aliquid minima est corporis commodi doloribus
              nostrum, minus et nobis? Accusantium asperiores adipisci labore
              nobis nisi aspernatur natus aperiam consequuntur dignissimos?
            </p>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
