import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <style jsx>{`
        .home_img_container {
          margin: 1.5rem;
        }
      `}</style>
      <div className={styles.container}>
        <Head>
          <title>Quick Coder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className="home_img_container">
            {/* You cannot use the Image component of NextJS while building a static site. So, we’ll replace that with the <img> Here’s the changed image component. */}
            {/* <Image
              style={{ borderRadius: "6.25rem" }}
              src="/home_image.jpg"
              width="170px"
              height="170px"
            ></Image> */}
            <img
              style={{ borderRadius: "6.25rem" }}
              src="/home_image.jpg"
              width="170px"
              height="170px"
              alt="Home image"
            />
          </div>
          <h1>Welcome to Quick Coder !</h1>

          <p className={styles.description}>A blog for Curious Minds.</p>
          <h2>Popular Blogs</h2>
          <div className={styles.grid}>
            <h3>How to learn React?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, aut
              ad non hic animi, aliquid minima est corporis commodi doloribus
              nostrum, minus et nobis? Accusantium asperiores adipisci labore
              nobis nisi aspernatur natus aperiam consequuntur dignissimos?
            </p>
            <h3>How to learn React?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, aut
              ad non hic animi, aliquid minima est corporis commodi doloribus
              nostrum, minus et nobis? Accusantium asperiores adipisci labore
              nobis nisi aspernatur natus aperiam consequuntur dignissimos?
            </p>
            <h3>How to learn React?</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, aut
              ad non hic animi, aliquid minima est corporis commodi doloribus
              nostrum, minus et nobis? Accusantium asperiores adipisci labore
              nobis nisi aspernatur natus aperiam consequuntur dignissimos?
            </p>
          </div>
        </main>
      </div>
    </>
  );
}
